#!/bin/bash
# Quick Railway Setup Script

echo "🚀 Railway Setup for Sunloc Server"
echo "===================================="
echo ""
echo "✅ Step 1: Commit and push code"
echo "   git add ."
echo "   git commit -m 'Railway PostgreSQL setup'"
echo "   git push"
echo ""
echo "✅ Step 2: Open https://railway.app/dashboard"
echo ""
echo "✅ Step 3: Click your project 'powerful-commitment'"
echo ""
echo "✅ Step 4: Look for 'postgres' service"
echo "   If NOT present:"
echo "     - Click '+ Add Service' → Database → PostgreSQL"
echo "     - Wait 60 seconds for it to initialize"
echo ""
echo "✅ Step 5: Click the 'postgres' service"
echo "   Go to 'Variables' tab"
echo "   Copy these values:"
echo "     - PGHOST"
echo "     - PGPORT"
echo "     - PGDATABASE"
echo "     - PGUSER"
echo "     - PGPASSWORD"
echo ""
echo "✅ Step 6: Click the 'sunloc-server' service"
echo "   Go to 'Variables' tab"
echo "   Add these NEW variables:"
echo ""
echo "     DB_HOST=postgres.railway.internal"
echo "     DB_PORT=5432"
echo "     DB_NAME=railway"
echo "     DB_USER=postgres"
echo "     DB_PASSWORD=<paste PGPASSWORD from step 5>"
echo "     PORT=3000"
echo "     NODE_ENV=production"
echo ""
echo "✅ Step 7: Wait for auto-redeploy"
echo "   Check the 'Logs' tab"
echo "   Look for: ✅ Connected to PostgreSQL"
echo ""
echo "✅ Step 8: Test"
echo "   Open: https://your-railway-url.railway.app/api/health"
echo ""
echo "Done! 🎉"
